### ISSUE TITLE
Custom password

### ISSUE THREAD

**Issue by honyczek** [jformacek/admpwd#1]
We use same password for each group of computers, so admins can remember which password to use. Would be possible to modify LAPS policy to enable custom password (entered by admin) or use the same password for a group of computers?

**Comment by jformacek** [comment]
Hello,
thanks for submitting the idea.
Actually, this is not the way we want to go. Reasons are:
- solution does password randomization, each machine takes care of own admin password, and we're focusing more on ways how to enable admins to use password without actually knowing it
- having the same password for group of computers would mean that password is either predictable (based on group membership) or flow completely opposite direction (from AD to machines)

Predictability of password is bad thing as it defeats security
Opposite direction password flow is difficult to make secure - this is why MS retired password distribution via GG Preferences (which you might have used before)

Would be good to know more about your use case to know how to help you different way - please share

Thank you,
Jiri
