### ISSUE TITLE
small issues

### ISSUE THREAD

**Issue by lvandenb** [jformacek/admpwd#7]
checking wrong variable : reading **&_pwdComplexity** but checking  **_pwdLength** 

```
	GetRegistryDWORD(hPolicyKey, PWD_COMPLEXITY_REG_VALUE, &_pwdComplexity);
	if (_pwdLength > MAX_PWD_LENGTH || _pwdLength < PWD_LENGTH) _pwdLength = PWD_LENGTH;
```

same for next **_pwdAge**

Expanding the #defines can be an issue, because it will append the text **//default** ?

```
#define MAX_PWD_COMPLEXITY	4	//default
#define PWD_LENGTH		12	//default
#define PWD_AGE_DAYS	30	//default

```

**Comment by jformacek** [comment]
Hello,
fixed. Thanks for reporting

Jiri
